"""add requested_branch_name to Workspace and naming_pattern to Project

Revision ID: 059f36aaa193
Revises: c8d4e5f6a7b8
Create Date: 2026-04-22 20:12:04.165765

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "059f36aaa193"
down_revision: str | None = "c8d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("naming_pattern", sa.String(), nullable=True))
    op.add_column("project_latest", sa.Column("naming_pattern", sa.String(), nullable=True))
    op.add_column("workspace", sa.Column("requested_branch_name", sa.String(), nullable=True))
    op.add_column("workspace_latest", sa.Column("requested_branch_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_latest", "requested_branch_name")
    op.drop_column("workspace", "requested_branch_name")
    op.drop_column("project_latest", "naming_pattern")
    op.drop_column("project", "naming_pattern")
    # ### end Alembic commands ###
