"""add target_branch to workspace

Revision ID: 0fb6dc48c8ef
Revises: 865d3a5b4f84
Create Date: 2026-02-19 19:41:30.038407

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fb6dc48c8ef"
down_revision: str | None = "865d3a5b4f84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("target_branch", sa.String(), nullable=True))
    op.add_column("workspace_latest", sa.Column("target_branch", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_latest", "target_branch")
    op.drop_column("workspace", "target_branch")
    # ### end Alembic commands ###
