"""add diff_status and diff_updated_at to workspace

Revision ID: 20fea77a3f5a
Revises: ad24ef11df19
Create Date: 2026-02-09 17:37:47.490486

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20fea77a3f5a"
down_revision: str | None = "ad24ef11df19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("diff_status", sa.String(), nullable=False, server_default="NONE"))
    op.add_column("workspace", sa.Column("diff_updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("workspace_latest", sa.Column("diff_status", sa.String(), nullable=False, server_default="NONE"))
    op.add_column("workspace_latest", sa.Column("diff_updated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_latest", "diff_updated_at")
    op.drop_column("workspace_latest", "diff_status")
    op.drop_column("workspace", "diff_updated_at")
    op.drop_column("workspace", "diff_status")
    # ### end Alembic commands ###
