"""add ci_babysitter_paused to workspace

Revision ID: 34fe61b617e6
Revises: b3f1a9c2d6e5
Create Date: 2026-06-22 20:56:23.997238

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34fe61b617e6"
down_revision: str | None = "b3f1a9c2d6e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="0" (False) so existing workspace rows backfill to not-paused.
    op.add_column("workspace", sa.Column("ci_babysitter_paused", sa.Integer(), nullable=False, server_default="0"))
    op.add_column(
        "workspace_latest", sa.Column("ci_babysitter_paused", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_latest", "ci_babysitter_paused")
    op.drop_column("workspace", "ci_babysitter_paused")
    # ### end Alembic commands ###
