"""add workspace_setup_command to Project

Revision ID: 9e05ec455f3d
Revises: 0bf9b0c50c83
Create Date: 2026-04-07 17:24:43.981674

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e05ec455f3d"
down_revision: str | None = "0bf9b0c50c83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("workspace_setup_command", sa.String(), nullable=True))
    op.add_column("project_latest", sa.Column("workspace_setup_command", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_latest", "workspace_setup_command")
    op.drop_column("project", "workspace_setup_command")
    # ### end Alembic commands ###
