"""add turn_metrics stopped and interrupted fields to chat messages

Replaces four no-op migrations (4b6e5dd43486, 34d5409840c7,
237ccbb5df42, cb8f90417e62) with a single revision.

No SQL changes are needed — the new fields live inside JSON blobs
and default to None / False, so existing data is unaffected.

Revision ID: eedceaef0697
Revises: d58cd1a270b9
Create Date: 2026-03-13 12:39:05.416841

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "eedceaef0697"
down_revision: str | None = "d58cd1a270b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
