"""add setup_command column

Revision ID: f332049181c5
Revises: 35cc9f0245b6
Create Date: 2026-04-28 16:04:26.230406

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f332049181c5"
down_revision: str | None = "35cc9f0245b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("setup_command", sa.String(), nullable=True))
    op.add_column("workspace_latest", sa.Column("setup_command", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_latest", "setup_command")
    op.drop_column("workspace", "setup_command")
    # ### end Alembic commands ###
