"""add setup_command_triggered to Workspace

Revision ID: f9c8fbb043ec
Revises: 9e05ec455f3d
Create Date: 2026-04-10 16:15:21.047469

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9c8fbb043ec"
down_revision: str | None = "9e05ec455f3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("setup_command_triggered", sa.Integer(), nullable=False, server_default="0"))
    op.add_column(
        "workspace_latest", sa.Column("setup_command_triggered", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_latest", "setup_command_triggered")
    op.drop_column("workspace", "setup_command_triggered")
    # ### end Alembic commands ###
