[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sculptor"
# this is a lie. The version file will be injected.
version = "0.0.0"
readme = "README.md"
dependencies = [
    "email-validator",
    "fastapi",
    "imbue-core",
    "loguru",
    "psycopg[binary]",
    "pydantic",
    "pydantic-settings",
    "pyjwt[crypto]",
    "pyre-check",
    "sentry-sdk",
    "sqlalchemy",
    "typeid-python",
    "typer",
]
requires-python = ">=3.11"

[tool.uv.sources]
imbue_core = { workspace = true }

[tool.setuptools.packages.find]
exclude = ["keys"]

[dependency-groups]
dev = [
    "filelock>=3.18.0",
    "pytest>=7.4.0",
    "pytest-xdist>=3.7.0",
]

[project.scripts]
sculptor_npm_run = "sculptor.scripts.npm_run:app"
