[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sculptor"

# This is going to be the true version.
version = "0.0.6"

readme = "README.md"
dependencies = [
    # Please add dev dependencies to dependency-groups.dev, not here.
    # Please keep these sorted alphabetically.
    "alembic>=1.16.1",
    "anthropic>=0.38.0",
    "coolname>=2.2.0",
    "email-validator",
    "fastapi",
    "filelock>=3.8.0",
    "loguru",
    "modal>=1.0.3",
    "psutil>=5.9.0",
    "psycopg[binary]",
    "pydantic-settings",
    "pyjwt[crypto]",
    "pyre-check",
    "requests>=2.28.0",
    "sentry-sdk",
    "splinter>=0.19.0",
    "sqlalchemy",
    "tomlkit>=0.13.0",
    "typeid-python",
    "typer",
    "uvicorn>=0.34.3",
    "watchdog>=6.0.0",
    "websockets>=15.0.1",

    # The following dependencies have been inlined from imbue_core.
    #
    # See ../imbue_core/pyproject.toml for the full files.
    #
    # We need them to be first-class dependencies so that platform-specific
    # libraries like pydantic can be pulled by the customer without needing to
    # be vendored.
    "anyio",
    "attrs",
    "boto3>=1.38.27",
    "cachetools",
    "cattrs",
    "grpclib>=0.4.7",
    "httpx",
    "inline-snapshot",
    "loguru",
    "pathspec",
    "posthog==5.4.0",
    "prometheus-client>=0.20.0",
    "pydantic-settings",
    "pydantic>=2.11.4",
    "pyhumps",
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "sentry-sdk",
    "tblib==2.0.0", # pinning because Hammers code relies on "get_locals"
    "tenacity>=8.2.2",
    "traceback-with-variables>=2.2.0",
    "yasoo",
    # End imbue_core inline
    # Do not add direct dependencies here.
]
requires-python = ">=3.11"

[tool.uv.sources]
imbue_core = { workspace = true }

[tool.setuptools.packages.find]
exclude = ["keys"]

[dependency-groups]
dev = [
    "filelock>=3.18.0",
    "websocket-client>=1.5.1",
    "imbue_core==0.0.9",
    "playwright==1.53.0",
    "pytest-playwright==0.7.0",
    "pytest-metadata==3.1.1",
    "pyfixfmt",
    "pytest-cov>=6.2.1",
    "pytest-xdist>=3.8.0",
    "pytest>=8.4.1",
    "sculptor_v0", # Tests still have a dependency on Sculptor v0
    "selenium>=4.0.0",
    "syrupy",
]

[project.scripts]
sculptor_npm_run = "sculptor.scripts.npm_run:app"
sculptor = "sculptor.cli.main:entrypoint"
sculptor_eslint_preprocess = "sculptor.scripts.eslint_preprocess:main"
