[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sculptor"
# this is a lie. The version file will be injected.
version = "0.0.0"
readme = "README.md"
dependencies = [
    # Please add dev dependencies to dependency-groups.dev, not here.
    "anthropic>=0.38.0",
    "email-validator",
    "fastapi",
    "loguru",
    "modal>=1.0.3",
    "psycopg[binary]",
    "pydantic",
    "pydantic-settings",
    "pyjwt[crypto]",
    "pyre-check",
    "pytest-xdist",
    "sentry-sdk",
    "sqlalchemy",
    "syrupy",
    "typeid-python",
    "typer",
    "filelock>=3.8.0",
    "psutil>=5.9.0",
    "pytest>=7.0.0",
    "requests>=2.28.0",
    "selenium>=4.0.0",
    "splinter>=0.19.0",
    "uvicorn>=0.34.3",
    "coolname>=2.2.0",
    "watchdog>=6.0.0",
]
requires-python = ">=3.11"

[tool.uv.sources]
imbue_core = { workspace = true }

[tool.setuptools.packages.find]
exclude = ["keys"]

[dependency-groups]
dev = [
    "filelock>=3.18.0",
    "pytest>=7.4.0",
    "pytest-xdist>=3.7.0",
    "pyfixfmt",
]

[project.scripts]
sculptor_npm_run = "sculptor.scripts.npm_run:app"
sculptor = "sculptor.cli.main:main"
