import type { KeybindingDefinition } from "./types.ts";

export const KEYBINDING_DEFINITIONS: ReadonlyArray<KeybindingDefinition> = [
  {
    id: "send_message",
    name: "Send message",
    description: "Send the current message",
    category: "chat",
    defaultBinding: "Meta+Enter",
  },
  {
    id: "interrupt_agent",
    name: "Stop agent",
    description: "Interrupt the running agent (when chat input is focused)",
    category: "chat",
    defaultBinding: "Ctrl+C",
  },
  {
    id: "new_workspace",
    name: "New workspace",
    description: "Create a new workspace",
    category: "workspaces",
    defaultBinding: "Meta+T",
  },
  {
    id: "open_workspace",
    name: "Go to workspace",
    description: "Open the command palette on the workspace switcher",
    category: "workspaces",
    defaultBinding: "Meta+P",
  },
  {
    id: "delete_workspace",
    name: "Delete workspace",
    description: "Delete the current workspace and all of its agents",
    category: "workspaces",
    defaultBinding: "Meta+Shift+W",
  },
  // The next_tab/previous_tab ids predate the sidebar workspace list (they cycled
  // the old tab strip); the ids are kept so users' persisted overrides still apply.
  {
    id: "next_tab",
    name: "Next workspace",
    description: "Switch to the next workspace",
    category: "workspaces",
    defaultBinding: "Meta+]",
  },
  {
    id: "previous_tab",
    name: "Previous workspace",
    description: "Switch to the previous workspace",
    category: "workspaces",
    defaultBinding: "Meta+[",
  },
  {
    id: "focus_input",
    name: "Focus input",
    description: "Focus the chat input field",
    category: "general",
    defaultBinding: "Meta+I",
  },
  {
    id: "chat_search",
    name: "Chat search",
    description: "Open or focus the chat search bar",
    category: "general",
    defaultBinding: "Meta+Shift+F",
  },
  {
    id: "find_in_file",
    name: "Find in file",
    description: "Open the in-file search bar in the diff viewer",
    category: "general",
    defaultBinding: "Meta+F",
  },
  {
    id: "command_palette",
    name: "Command palette",
    description: "Open the command palette to search and run commands",
    category: "general",
    defaultBinding: "Meta+K",
  },
  {
    id: "help",
    name: "Help",
    description: "Toggle the help dialog",
    category: "general",
    defaultBinding: "Meta+/",
  },
  {
    id: "home",
    name: "Home",
    description: "Open the home page",
    category: "navigation",
    defaultBinding: "Meta+.",
  },
  {
    id: "settings",
    name: "Settings",
    description: "Open the settings page",
    category: "general",
    defaultBinding: "Meta+,",
  },
  {
    id: "toggle_theme",
    name: "Toggle theme",
    description: "Switch between light and dark mode",
    category: "general",
    defaultBinding: "Meta+Shift+D",
  },
  {
    id: "toggle_left_panel",
    name: "Toggle left panel",
    description: "Show or hide the left sidebar",
    category: "general",
    defaultBinding: "Meta+Alt+ArrowLeft",
  },
  {
    id: "toggle_bottom_panel",
    name: "Toggle bottom panel",
    description: "Show or hide the bottom panel",
    category: "general",
    defaultBinding: "Meta+Alt+ArrowDown",
  },
  {
    id: "toggle_right_panel",
    name: "Toggle right panel",
    description: "Show or hide the right sidebar",
    category: "general",
    defaultBinding: "Meta+Alt+ArrowRight",
  },
  {
    id: "toggle_sidebar",
    name: "Toggle sidebar",
    description: "Collapse or expand the workspace sidebar",
    category: "general",
    defaultBinding: "Meta+Alt+B",
  },
  {
    id: "maximize_section",
    name: "Maximize section",
    description: "Maximize or restore the active section",
    category: "panels",
    defaultBinding: "Meta+Shift+M",
  },
  {
    id: "open_layouts",
    name: "Layouts",
    description: "Open the layouts switcher",
    category: "panels",
    defaultBinding: "Meta+Shift+L",
  },
  {
    // Active only while the layouts switcher is open (the switcher owns a
    // capture-phase listener); opens the more-options popover for the highlighted
    // layout.
    id: "layout_more_options",
    name: "Layout options",
    description: "Open more options for the highlighted layout in the switcher",
    category: "panels",
    defaultBinding: "Meta+J",
  },
  {
    id: "next_section",
    name: "Next section",
    description: "Cycle to the next section (including split sub-sections)",
    category: "navigation",
    defaultBinding: "Ctrl+`",
  },
  {
    id: "previous_section",
    name: "Previous section",
    description: "Cycle to the previous section (including split sub-sections)",
    category: "navigation",
    defaultBinding: "Ctrl+Shift+`",
  },
  {
    id: "next_panel",
    name: "Next panel",
    description: "Cycle to the next panel within the active section",
    category: "panels",
    defaultBinding: "Meta+Alt+]",
  },
  {
    id: "previous_panel",
    name: "Previous panel",
    description: "Cycle to the previous panel within the active section",
    category: "panels",
    defaultBinding: "Meta+Alt+[",
  },
  {
    id: "previous_agent",
    name: "Previous agent",
    description: "Switch to the agent on the left",
    category: "workspaces",
    defaultBinding: "Meta+Shift+[",
  },
  {
    id: "next_agent",
    name: "Next agent",
    description: "Switch to the agent on the right",
    category: "workspaces",
    defaultBinding: "Meta+Shift+]",
  },
  {
    id: "new_agent",
    name: "New agent",
    description: "Create a new agent in the current workspace",
    category: "workspaces",
    defaultBinding: "Meta+Shift+T",
  },
  {
    id: "open_in_app",
    name: "Open in app",
    description: "Open the repo in the preferred external app",
    category: "general",
    defaultBinding: "Meta+O",
  },
  {
    id: "toggle_tool_density",
    name: "Toggle tool call density",
    description: "Switch chat between compact pill and expanded row layouts for tool calls",
    category: "chat",
    defaultBinding: "Meta+Shift+E",
  },
  {
    id: "clear_terminal",
    name: "Clear terminal",
    description: "Wipe the active terminal's screen and scrollback (when the terminal is focused)",
    category: "terminal",
    defaultBinding: "Ctrl+L",
  },
];
