[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:wandb.*:
    ignore::DeprecationWarning:graphql.*:
    ignore::DeprecationWarning:notebook.*:
    ignore::DeprecationWarning:nptyping.*:
markers =
    integration_test: <10 seconds test that can use any resource
    slow_integration_test: like integration tests but can take up to 100 seconds
    needs_claude_code: needs the Claude Code CLI to be installed
    fast_and_cheap: quick tests with no external resource needs
addopts =
    --ignore=quarantine
    --ignore-glob=**/quarantine/**
    --ignore-glob=**/notebooks/**
