// Note, some linting rules conforming to the style guide at https://mkosir.github.io/typescript-style-guide/
import js from "@eslint/js";
import stylisticPlugin from "@stylistic/eslint-plugin";
import typescriptPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import prettierConfig from "eslint-config-prettier/flat";
import checkFilePlugin from "eslint-plugin-check-file";
import cssPlugin from "eslint-plugin-css";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const importPlugin = require("eslint-plugin-import");
import prettierPluginConfig from "eslint-plugin-prettier/recommended";
import reactPlugin from "eslint-plugin-react";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import reactRefreshPlugin from "eslint-plugin-react-refresh";
import simpleImportSortPlugin from "eslint-plugin-simple-import-sort";
import storybookPlugin from "eslint-plugin-storybook";
import globals from "globals";
import tseslint from "typescript-eslint";

// A page owns one routed surface; shared code moves up to components/ or
// common/ rather than being reached across pages. See frontend_structure.md.
const PAGE_ISOLATION_MESSAGE =
  "A page must not import from another page; move shared code up to components/ or common/. See frontend_structure.md.";

// Default export is expected by eslint:
// eslint-disable-next-line import/no-default-export
export default tseslint.config(
  // Global ignores must come first
  {
    ignores: [
      ".prettierrc.cjs",
      ".storybook",
      "babel.config.ts",
      "coverage/**",
      "dist",
      "eslint.config.ts",
      "jest.config.ts",
      "jest.setup.ts",
      "postcss.config.js",
      "scripts/**",
      "src/api/**",
      "**/build/**",
      "src/**/generated-*.ts",
      "src/**/generated-*.tsx",
      "src/quarantine/**",
      "src/views/tasks_deprecated/**",
      "tailwind.config.js",
      "vite.base.config.ts",
      "vite.web.config.ts",
      "out/**",
      "storybook-static/**",
      // Built plugin output sits in public/ and is not part of the host's TS
      // program. (The /plugin-runtime/ stubs are generated by a Vite plugin —
      // see vite-plugins/plugin-runtime-stubs.ts — not checked in here.)
      "public/plugins/**",
      // Source for runtime-loaded plugins is its own Vite project, not in
      // the host's tsconfig.
      "plugins/**",
    ],
  },
  // NOTE: turns off all rules that may conflict with prettier
  // https://github.com/prettier/eslint-config-prettier
  prettierConfig,
  // Run prettier as an eslint rule: https://github.com/prettier/eslint-plugin-prettier
  prettierPluginConfig,
  js.configs.recommended,
  tseslint.configs.recommended,

  reactPlugin.configs.flat.recommended,
  reactPlugin.configs.flat["jsx-runtime"],
  reactHooksPlugin.configs.flat["recommended-latest"],
  reactRefreshPlugin.configs.vite,
  importPlugin.configs.typescript,
  cssPlugin.configs["flat/recommended"],
  storybookPlugin.configs["flat/recommended"],

  // Merging this into customConfig results in the following:
  //
  // Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
  {
    settings: {
      react: {
        version: "detect",
      },
      // Teach eslint-plugin-import the `~/` tsconfig path alias (and TS
      // extensions) so the import/no-restricted-paths layering below can follow
      // `~/…` specifiers to real files. Without this the node resolver silently
      // fails to resolve aliased imports and the boundary rule skips them.
      "import/resolver": {
        typescript: {
          project: ["./tsconfig.json", "./tsconfig.node.json"],
        },
      },
    },
  },
  {
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        project: ["./tsconfig.json", "./tsconfig.node.json"],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.browser,
        ...globals.es2020,
        ...globals.node,
      },
    },
    plugins: {
      "@stylistic": stylisticPlugin,
      "@typescript-eslint": typescriptPlugin,
      import: importPlugin,
      css: cssPlugin,
      "simple-import-sort": simpleImportSortPlugin,
    },
    rules: {
      // React Compiler diagnostics from eslint-plugin-react-hooks 7.
      // `preserve-manual-memoization` and `incompatible-library` only change
      // anything once the React Compiler is enabled (it is not): they flag
      // working code the compiler merely cannot auto-optimize, so they stay off
      // until the compiler is turned on. The rest are enabled. rules-of-hooks
      // and exhaustive-deps stay active throughout.
      "react-hooks/refs": "error",
      "react-hooks/set-state-in-effect": "error",
      "react-hooks/immutability": "error",
      "react-hooks/preserve-manual-memoization": "off", // deferred: needs React Compiler
      "react-hooks/static-components": "error",
      "react-hooks/incompatible-library": "off", // deferred: needs React Compiler
      "react-hooks/use-memo": "error",
      "react-hooks/purity": "error",
      "react-hooks/globals": "error",

      /*
        Rules copied from https://mkosir.github.io/typescript-style-guide/ on 2025-06-04,
        with adaptions noted.

        If the style guide has updated,
        look for "📏" in the page and update the following.
      */
      // From the section "Types":
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/ban-ts-comment": ["error", { "ts-expect-error": "allow-with-description" }],
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/array-type": [
        "error",
        {
          default: "generic",
          // This is extra from us
          readonly: "generic",
        },
      ],
      "@typescript-eslint/consistent-type-imports": "error",

      // From the section "Functions":
      // This is only recommended in the open-source style guide,
      // but our style guide enforces this.
      "@typescript-eslint/explicit-function-return-type": "error",
      // Arrow functions everywhere, not just components (components are
      // covered by react/function-component-definition below).
      "func-style": ["error", "expression"],

      // From the section "Variables":
      "no-restricted-syntax": [
        "error",
        {
          selector: "TSEnumDeclaration",
          message: "Replace enum with a literal type or a const assertion.",
        },
      ],

      // From the section "Naming":
      /* Imports: https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#rules */
      "import/no-default-export": "error",

      // Import layering — keeps the dependency graph flowing one way, matching
      // docs/development/style/frontend_structure.md: app/ is the composition
      // root and may import anything; a page never imports another page;
      // components/ (shared UI) never reaches into pages/; common/ (shared
      // non-UI) never reaches up into components/, pages/, the app shell, or the
      // electron main process; and electron/ (main process) never imports
      // renderer UI.
      //
      // Every `except` here is TEMPORARY and mirrored in the "Import-boundary
      // exceptions (temporary)" section of agent_docs/scu1746/decisions.md, each
      // grouped by the follow-up that deletes it (e.g. promoting workspace
      // layout state into common/state). Do NOT add a new except to dodge a
      // boundary — move the shared code to its correct layer instead.
      "import/no-restricted-paths": [
        "error",
        {
          basePath: import.meta.dirname,
          zones: [
            {
              target: "./src/common",
              from: "./src/components",
              except: [
                // commandPalette command/context-action state read by the
                // workspace state hooks (ruling 4): removed when the palette
                // inverts to command registration.
                "./commandPalette/contextActions/atoms/contextActions.ts",
                "./commandPalette/utils/commandActions.ts",
                // useCreateWorkspace reads the new-workspace form atoms: removed
                // when those atoms move to common/state.
                "./newWorkspace/newWorkspaceAtoms.ts",
              ],
              message: "common/ is shared non-UI; it must not import from components/. See frontend_structure.md.",
            },
            {
              target: "./src/common",
              from: "./src/pages",
              except: [
                // Workspace layout + panel state lives feature-side (ruling 4
                // fallback); common/state hooks that orchestrate it read it
                // here. Removed when layout state is promoted to common/state.
                "./workspace/layout",
                "./workspace/diffPanel/atoms/diffPanel.ts",
                "./workspace/panels/browser/atoms/browser.ts",
                "./workspace/panels/workspaceAgentActions.ts",
                "./workspace/panels/fileBrowser/types/fileBrowser.ts",
              ],
              message: "common/ is shared non-UI; it must not import from pages/. See frontend_structure.md.",
            },
            {
              target: "./src/common",
              from: "./src/electron",
              except: [
                // Platform detection (isMac / isElectron / getMetaKey) is shared
                // glue that still lives in electron/. Removed when platform.ts
                // moves to common/.
                "./platform.ts",
              ],
              message:
                "common/ is shared non-UI; it must not import from the electron main process. See frontend_structure.md.",
            },
            {
              target: "./src/components",
              from: "./src/pages",
              except: [
                // Palette + shared widgets currently read workspace feature
                // state (ruling 4). Removed as each state module moves to its
                // correct shared layer.
                "./workspace/layout",
                "./workspace/hooks/useTimedLatch.ts",
                "./workspace/diffPanel/atoms/diffPanel.ts",
                "./workspace/diffPanel/types/diffPanel.ts",
                "./workspace/panels/fileBrowser/atoms/fileBrowser.ts",
                "./workspace/panels/fileBrowser/fileIcons.ts",
                "./workspace/chat/atoms/chat.ts",
                "./workspace/chat/chipRowUtils.ts",
                "./settings/sections.ts",
              ],
              message: "components/ is shared UI; it must not import from pages/. See frontend_structure.md.",
            },
            // Nothing below the shell imports the shell.
            {
              target: ["./src/common", "./src/components"],
              from: "./src/app",
              message: "app/ is the composition root; lower layers must not import it. See frontend_structure.md.",
            },
            // The electron main process must never import renderer UI.
            {
              target: "./src/electron",
              from: ["./src/components", "./src/pages", "./src/app"],
              message: "electron/ is the main process; it must not import renderer UI. See frontend_structure.md.",
            },
            // A page never imports another page. Each zone forbids importing
            // anything under src/pages except the page's own subtree; a handful
            // of temporary cross-page excepts are catalogued in decisions.md.
            {
              target: "./src/pages/addWorkspace",
              from: "./src/pages",
              except: ["./addWorkspace"],
              message: PAGE_ISOLATION_MESSAGE,
            },
            {
              target: "./src/pages/error",
              from: "./src/pages",
              except: ["./error"],
              message: PAGE_ISOLATION_MESSAGE,
            },
            {
              target: "./src/pages/home",
              from: "./src/pages",
              except: [
                "./home",
                // RecentWorkspaces is shared by home + addWorkspace: removed
                // when it is promoted to components/.
                "./addWorkspace/components/RecentWorkspaces.tsx",
              ],
              message: PAGE_ISOLATION_MESSAGE,
            },
            {
              target: "./src/pages/onboarding",
              from: "./src/pages",
              except: ["./onboarding"],
              message: PAGE_ISOLATION_MESSAGE,
            },
            {
              target: "./src/pages/settings",
              from: "./src/pages",
              except: [
                "./settings",
                // PiLoginTerminal reuses the workspace terminal hook: removed
                // when useTerminal is promoted to common/.
                "./workspace/panels/useTerminal.ts",
              ],
              message: PAGE_ISOLATION_MESSAGE,
            },
            {
              target: "./src/pages/workspace",
              from: "./src/pages",
              except: [
                "./workspace",
                // ChatInput reads the SettingsSection enum: removed when it
                // moves to common/.
                "./settings/sections.ts",
              ],
              message: PAGE_ISOLATION_MESSAGE,
            },
          ],
        },
      ],
      // The open-source style guide defines boolean, typeAlias
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "variable",
          types: ["boolean"],
          format: ["PascalCase"],
          prefix: ["is", "does", "are", "should", "has", "can", "did", "will"],
        },
        {
          selector: "typeAlias",
          format: ["PascalCase"],
        },
        {
          // Generic type parameter must start with letter T, followed by any uppercase letter.
          selector: "typeParameter",
          format: ["PascalCase"],
          custom: { regex: "^T[A-Z]?", match: true },
        },
        // This is extra from us
        {
          selector: "variable",
          types: ["function"],
          format: ["camelCase", "PascalCase"],
        },
        // maybe CONSTANT_CASE for as const top-level
        // excluding https://mkosir.github.io/typescript-style-guide/#generics as idk if I want to enforce that

        //  we'll do the opposite - acronym should be uppercase like in python
        // https://mkosir.github.io/typescript-style-guide/#abbreviations--acronyms
      ],
      "react/jsx-handler-names": [
        "error",
        {
          eventHandlerPrefix: "handle",
          eventHandlerPropPrefix: "on",
        },
      ],
      "react/hook-use-state": "error",

      // We use TypeScript for type checking, so no need for prop-types.
      "react/prop-types": "off",

      // We don't use vitest,
      // so we don't include the rules from the "Test" section.

      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],

      /* Eslint stylistic: https://eslint.style/packages/default */
      "@stylistic/padding-line-between-statements": [
        "error",
        { blankLine: "always", prev: "block", next: "block" },
        { blankLine: "always", prev: "block-like", next: "block-like" },
      ],

      /* Typescript Eslint: https://typescript-eslint.io/rules/ */
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],

      // Types
      "@typescript-eslint/no-explicit-any": "error",
      // not sure about this - seems close to an explicit runtime assertion intended to be caught higher up
      // "@typescript-eslint/no-non-null-assertion": "error",

      // Functions
      // only use 1 object param
      // "max-params": "off",
      // "@typescript-eslint/max-params": ["warn", { max: 1 }],

      // Variables
      "@typescript-eslint/prefer-as-const": "error",

      "@typescript-eslint/no-restricted-types": [
        "error",
        {
          types: {
            "React.FC": "Define the component props and return type explicitly.",
          },
        },
      ],

      /* React: https://github.com/jsx-eslint/eslint-plugin-react?tab=readme-ov-file#list-of-supported-rules */
      "react/function-component-definition": [
        "error",
        {
          namedComponents: "arrow-function",
          unnamedComponents: "arrow-function",
        },
      ],
      "react/display-name": "off",
      "react/jsx-curly-brace-presence": [
        "error",
        {
          props: "never",
          children: "never",
        },
      ],

      // configure simple-import-sort plugin
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
    },
  },
  // File/folder naming enforcement (docs/development/style/frontend_structure.md):
  // directories are camelCase, and the generic basenames the style guide bans
  // (utils/helpers/hooks/atoms/types/misc) fail the blocklist so plumbing files
  // are named for their topic instead. Scoped to source modules; `__tests__` is
  // the one non-camelCase folder we allow.
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      "check-file": checkFilePlugin,
    },
    rules: {
      "check-file/folder-naming-convention": ["error", { "src/**/": "CAMEL_CASE" }, { ignoreWords: ["__tests__"] }],
      "check-file/filename-blocklist": [
        "error",
        {
          "**/utils.ts": "*.<topic>.ts",
          "**/helpers.ts": "*.<topic>.ts",
          "**/hooks.ts": "use<Name>.ts",
          "**/atoms.ts": "*.<topic>.ts",
          "**/types.ts": "*.<topic>.ts",
          "**/misc.ts": "*.<topic>.ts",
        },
        {
          errorMessage:
            'Generic basename "{{ target }}" is banned (matched "{{ pattern }}"). Name the topic, or the feature for a lone file (e.g. atoms/selection.ts, utils/formatting.ts). See frontend_structure.md.',
        },
      ],
    },
  },
);
