"""MIGRATION_MESSAGE=updated content block and artifact types

Revision ID: 203b2a5d014e
Revises: a3d964fe7d6d
Create Date: 2025-08-11 13:20:25.564471

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "203b2a5d014e"
down_revision: str | None = "a3d964fe7d6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
