"""make error optional for agent warning message

Revision ID: 21c68f672a21
Revises: 4dc28ae7e36c
Create Date: 2025-07-11 17:53:07.266130

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "21c68f672a21"
down_revision: str | None = "4dc28ae7e36c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
