"""unknown

Revision ID: 2995f89f9123
Revises: c2e59e2da012
Create Date: 2025-09-11 17:35:26.744031

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "2995f89f9123"
down_revision: str | None = "c2e59e2da012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
