"""add environment_id to task state

Revision ID: 3ca4c45c9b2c
Revises: 965f5ec3dd2f
Create Date: 2025-09-21 09:46:23.214204

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "3ca4c45c9b2c"
down_revision: str | None = "965f5ec3dd2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
