"""MIGRATION_MESSAGE=change ID types

Revision ID: 444c63d27956
Revises: 551636ad80f1
Create Date: 2025-08-11 20:16:26.287837

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "444c63d27956"
down_revision: str | None = "551636ad80f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
