"""MIGRATION_MESSAGE=added new task status type

Revision ID: 551636ad80f1
Revises: 203b2a5d014e
Create Date: 2025-08-11 16:25:35.526149

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "551636ad80f1"
down_revision: str | None = "203b2a5d014e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
