"""Update ResponseBlockAgentMessage schema

Revision ID: 89389e1b9e5c
Revises: a71cb52b3534
Create Date: 2025-09-29 13:22:32.433948

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "89389e1b9e5c"
down_revision: str | None = "a71cb52b3534"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
