"""remove mount config value

Revision ID: 965f5ec3dd2f
Revises: fbe6298ff829
Create Date: 2025-09-20 07:40:04.611480

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "965f5ec3dd2f"
down_revision: str | None = "fbe6298ff829"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
