"""Added consent markup to GitCommitAndPushUserMessage and GitPullUserMessage

Revision ID: a3d964fe7d6d
Revises: d149ce46d5aa
Create Date: 2025-08-01 08:02:47.794312

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "a3d964fe7d6d"
down_revision: str | None = "d149ce46d5aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
