"""track if container snapshots are clean

Revision ID: a71cb52b3534
Revises: b777f4232d0b
Create Date: 2025-09-29 10:27:33.186167

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "a71cb52b3534"
down_revision: str | None = "b777f4232d0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
