"""change default for sandboxes

Revision ID: c2e59e2da012
Revises: 038c875211f1
Create Date: 2025-09-11 10:44:06.709182

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "c2e59e2da012"
down_revision: str | None = "038c875211f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
