"""Added logging annotations to various message fields

Revision ID: d149ce46d5aa
Revises: e5ae8d9bc76b
Create Date: 2025-07-31 15:13:20.498599

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "d149ce46d5aa"
down_revision: str | None = "e5ae8d9bc76b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
