"""Added logging annotations to various message fields

Revision ID: e5ae8d9bc76b
Revises: e8793e0c1b79
Create Date: 2025-07-31 06:57:20.568087

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "e5ae8d9bc76b"
down_revision: str | None = "e8793e0c1b79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
