"""Adds new LocalDevcontainerImageConfig

Revision ID: e6789637fc58
Revises: e0d5fc28d54a
Create Date: 2025-08-26 11:05:22.384066

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "e6789637fc58"
down_revision: str | None = "e0d5fc28d54a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
