"""context compaction update

Revision ID: e86aee515743
Revises: e05f6d83c837
Create Date: 2025-08-20 10:39:42.997189

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "e86aee515743"
down_revision: str | None = "e05f6d83c837"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
