"""UpdateLocalSyncRunnerMessage.notices, Update and Resume subtypes

Revision ID: f35851ffaae2
Revises: 37411143b314
Create Date: 2025-08-18 20:34:19.228638

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "f35851ffaae2"
down_revision: str | None = "37411143b314"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
