"""remove more messages

Revision ID: fec9f27c7f2e
Revises: e86aee515743
Create Date: 2025-08-21 10:04:01.555488

"""

from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fec9f27c7f2e"
down_revision: str | None = "e86aee515743"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        DELETE FROM saved_agent_message
        WHERE json_extract(message, '$.object_type') IN (
            'CompletedStderrAgentMessage',
            'UpdateGoalAgentMessage',
            'WriteFileUserMessage'
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
