# Imbue's default base image to supply the agentic environment.
# This is meant to be overrideable by the user.

FROM ubuntu:24.04@sha256:7c06e91f61fa88c08cc74f7e1b7c69ae24910d745357e0dfe1d2c0322aaf20f9

# Add a dev user that can sudo.
RUN useradd -m -s /bin/bash dev

# A bit of a "kitchen sink" to get a user started.
# Note that we purposefully repeat python and git even though they're already in the Imbue control plane,
# because the Imbue control plane is not meant to be exposed to the user..

# See also: https://github.com/openai/codex-universal/blob/main/Dockerfile

RUN apt-get update

# These are split apart to create a few layers that can be pulled in parallel.
RUN apt-get install -y --no-install-recommends \
    binutils=2.42-* \
    build-essential \
    build-essential=12.10* \
    cmake \
    curl \
    default-libmysqlclient-dev=1.1.* \
    dnsutils=1:9.18.* \
    gettext=0.21-* \
    gh \
    git-lfs=3.4.* \
    git=1:2.43.* \
    gnupg=2.4.* \
    gnupg2 \
    inotify-tools=3.22.*
RUN apt-get install -y --no-install-recommends \
    iputils-ping=3:20240117-* \
    jq \
    jq=1.7.* \
    less \
    libc6-dev=2.39-* \
    libc6=2.39-* \
    libstdc++-13-dev=13.3.* \
    make=4.3-* \
    man-db \
    moreutils=0.69-* \
    nano \
    ncdu \
    neovim \
    pipx=1.4.* \
    pkg-config=1.8.* \
    protobuf-compiler=3.21.* \
    python3-dev
RUN apt-get install -y --no-install-recommends \
    ripgrep=14.1.* \
    rsync=3.2.* \
    sqlite3=3.45.* \
    strace \
    sudo=1.9.* \
    tzdata=2025b-* \
    unzip=6.0-* \
    vim \
    wget=1.21.* \
    xz-utils=5.6.* \
    zip=3.0-*


# Gives everyone sudo access.  Makes sense for a devcontainer.
RUN echo "ALL ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install uv.
# See: https://github.com/astral-sh/uv/pkgs/container/uv/versions?filters%5Bversion_type%5D=tagged
COPY --from=ghcr.io/astral-sh/uv:0.8.18@sha256:62022a082ce1358336b920e9b7746ac7c95b1b11473aa93ab5e4f01232d6712d /uv /uvx /bin/

# The default devcontainer user is root.
USER root
