#!/usr/bin/env bash
# This script sets the right environment for the imbue CLI to work, including the certificate environment variable.
source /imbue/env/env_for_claude.sh
# Reset to the user's original PATH, plus just a few of our things.
export PATH=${_IMBUE_USER_ORIGINAL_PATH}:/imbue_addons/agent_path_extension_bin/
exec /imbue/nix_bin/claude "$@"
